version: '3.1'
services:
  kytos-server:
    image: italovalcy/kytos
    build: .
    command: -E
    restart: always
    ports:
      - 6653:6653

  apache-server:
    image: italovalcy/apache
    build:
      context: .
      dockerfile: Dockerfile-apache
    restart: always
    environment:
      KYTOS_SERVER: "kytos-server"
    links:
      - "kytos-server"
    depends_on:
      - "kytos-server"
    ports:
      - 8443:443
